<?php

namespace app\modules\admin\models;

use Yii;
use yii\db\ActiveQuery;
use yii\web\UploadedFile;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property string $title
 * @property string $content
 * @property float $price
 * @property float $old_price
 * @property string|null $description
 * @property string|null $keywords
 * @property string $img
 * @property   $file
 * @property-read ActiveQuery $category
 * @property int $is_offer
 */
class Product extends \yii\db\ActiveRecord
{
	public $file;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

	public function getCategory(): ActiveQuery
	{
		return $this->hasOne(Category::class, ['id' => 'category_id']);
	}

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'title', 'content'], 'required'],
            [['category_id', 'is_offer'], 'integer'],
            [['content'], 'string'],
            [['price', 'old_price'], 'number'],
            [['price', 'old_price'], 'default', 'value' => 0],
            [['img'], 'default', 'value' => 'products/no-image.png'],
			[['description', 'keywords'], 'string'],
			[['title', 'img'], 'string', 'max' => 255],
			[['file'], 'file', 'extensions' => 'png, jpg'],
            [['title', 'description', 'keywords', 'img'], 'string', 'max' => 255],

//	        [['file'], 'image'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'title' => 'Title',
            'content' => 'Content',
            'price' => 'Price',
            'old_price' => 'Old Price',
            'description' => 'Description',
            'keywords' => 'Keywords',
            'img' => 'Img',
            'file' => 'Фото',
            'is_offer' => 'Is Offer',
        ];
    }

	public function beforeSave($insert)
	{
//		$this->img = 'uploads/' . $file->baseName . '.' . $file->extension;
//		$file->saveAs($this->img);
		if ($file = UploadedFile::getInstance($this, 'file')) {
			$dir = 'products/' . date("Y-m-d") . '/';
			if (!is_dir($dir)) {
				mkdir($dir);
			}
			$file_name = uniqid() . '_' . $file->baseName . '.' .  $file->extension;
			$this->img = $dir . $file_name;
			$file->saveAs($this->img);
		}

		return parent::beforeSave($insert); // TODO: Change the autogenerated stub
	}
}
