<?php

namespace app\controllers;

use yii\web\BadRequestHttpException;
use yii\web\Controller;

class AppController extends Controller
{

	/**
	 * @throws BadRequestHttpException
	 */
	public function beforeAction($action): bool
	{
        $this->view->title = \Yii::$app->name;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

	protected function setMeta($title = null, $keywords = null, $description = null): void
	{
		$this->view->title = $title;
		$this->view->registerMetaTag(['name' => 'keywords', 'content' => "$keywords"]);
		$this->view->registerMetaTag(['name' => 'description', 'content' => "$description"]);
	}

}